api:
  base_url: "https://api.ihc-attribution.com/v1/compute_ihc"
  api_key: "e9395de1-826b-43c9-a551-32dd6f690258"
  conv_type_id: "data_engineering_challenge"
  batch_size: 200
  retry_count: 3
  retry_delay: 5
  timeout: 30

database:
  db_name: "challenge.db"
  sql_name: "challenge_db_create.sql"
  data_dir: "data"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

output:
  file_path: "output/channel_reporting.csv"